# -*- coding: utf-8 -*-
"""Project_Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FG9SQZXCAaed0JMe-uhbNvZk1zr9_z75

## Use fune-tuned model for inference
"""

text = 'Bermuda\'s COVID-19 cases surpass 100 The Ministry of Health in Bermuda has confirmed a newspaper report that 10 residents from the Westmeath Residential and Nursing Home had tested positive for COVID-19, taking the island’s total confirmed cases past the 100 mark. A further 213 of the 1,173 tests that have been carried out, were received from across Bermuda yesterday and today, all of which were negative, the ministry said on Saturday night. These included 74 essential workers, who received negative results at the new drive-through testing facility at Southside, near the international airport, which remains closed to regular commercial flights. Bermuda is under lockdown until May 2, although more businesses are being allowed to reopen on a limited basis. The island has a total of 109 confirmed cases, of which 65 are active. Eleven people are in hospital, 54 are being actively monitored and 39 have recovered. Five people have died.'

from transformers import pipeline
import torch

# Define the variable right before using it
repo_name = "willphan1712/fake_news_detection"

print(f"Loading model: {repo_name}")

# --- Using pipeline (The easy way) ---
print("\n--- Testing with pipeline ---")
# This task 'text-classification' is a guess.
# You may need to change it based on the model card.
task = "text-classification"
predictor = pipeline(task, model=repo_name)

result = predictor(text, truncation=True, max_length=512)

if (result[0]['label'] == 'LABEL_1'):
    print('This is a good heading')
else:
    print('This is a misleading heading')